routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('words', 'WordListController');
Route::resource('dangers', 'DangerController');

app/Danger.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Danger extends Model
{
    protected $table = "danger";

    protected $fillable = ['word'];

    public $timestamps = false;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/WordList.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WordList extends Model
{
    protected $table = "words_list";

    protected $fillable = ['title', 'danger'];

    public $timestamps = false;
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DangerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Danger;
class DangerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dangers = Danger::get();

        $route = "dangers";

        return view('pages.danger',['dangers'=>$dangers, 'route'=>$route]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $danger = Danger::updateOrCreate(['word'=>$request->get('word')]);

        return redirect()->route('dangers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $el = Danger::find($id);
        if($el){
            $el->delete();
        }
        return redirect()->route('dangers.index');
    }
}

app/Http/Controllers/WordListController.php
<?php

namespace App\Http\Controllers;
use App\WordList;
use App\Danger;
use Illuminate\Http\Request;

class WordListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $words = WordList::get();

        $route = "words";

        return view('pages.word',['words'=>$words, 'route'=>$route]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dangers = Danger::get();

        $wordToSave = [];

        if($request->ajax()){

            $data = $request->get('data');

            $array_words = explode(' ', $data);

            $length = count($array_words);

            $perc = 100/$length;

            $toSave = 0;

            foreach ($dangers as $danger){


                foreach ($array_words as $key=>$value){

                    if($danger->word === $value){
                        $array_words[$key]= "<strong>$value</strong>";

                        $toSave += $perc;

                    }

                }

            }
            $readyWords = implode(' ', $array_words);

            $words = WordList::updateOrCreate([
               'title'=>$readyWords,
               'danger'=>$toSave
            ]);

            return redirect()->route('words.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $el = WordList::find($id);
        if($el){
            $el->delete();
        }
        return redirect()->route('words.index');
    }
}

resources/views/inc/form.blade.php
<form method="post" action="{{route($route.".store")}}">
    {{csrf_field()}}
    <div class="form-row align-items-center">
        <div class="col-sm-3 my-1">
            <label class="sr-only" for="inlineFormInputName">Заметка</label>
            <input type="text" name="word" class="form-control" id="inlineFormInputName" placeholder="Добавить заметку">
        </div>
        <div class="col-auto my-1">
            <button type="submit" id="submit" class="btn btn-success">Добавить</button>
        </div>
    </div>
</form>

resources/views/layout/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

<div class="container">
    @yield('body')
</div>

<script src="{{asset('js/app.js')}}"></script>
@yield('script')
</body>
</html>

resources/views/pages/danger.blade.php
@extends("layout.app")

@section('body')
    @isset($dangers)
        <div class="row">
            <div class="col-md-10">
                @include('inc.form', [$route])
            </div>
            <div class="col-md-2 text-center btn-group-vertical">
                <a class="btn btn-primary" href="{{route('words.index')}}">Заметки</a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table table-dark">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Слова</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($dangers as $danger)
                        <tr>
                            <th scope="row">{{ $loop->index + 1  }}</th>
                            <td>{!! $danger->word !!}</td>
                            <td>
                                <span>
                                    <form action="{{route('dangers.destroy',$danger->id)}}" method="post">
                                        @csrf
                                        {{method_field('delete')}}
                                        <button style="cursor: pointer"><i style="color: red;" class="far fa-trash-alt"></i></button>
                                    </form>
                                </span>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    @endisset
@endsection

resources/views/pages/word.blade.php
@extends("layout.app")

@section('body')
    @isset($words)
        <div class="row">
            <div class="col-md-9">
                @include('inc.form')
            </div>
            <div class="col-md-3">
                <a class="btn btn-info" href="{{route('dangers.index')}}">Списка опасных слов</a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">заметки</th>
                        <th scope="col">Процент опасности</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($words as $word)
                        <tr>
                            <th scope="row">{{ $loop->index + 1}}</th>
                            <td>{!! $word->title !!}</td>
                            <td>{!! $word->danger !!}%</td>
                            <td>
                                <span>
                                    <form action="{{route('words.destroy',$word->id)}}" method="post">
                                        @csrf
                                        {{method_field('delete')}}
                                        <button style="cursor: pointer"><i style="color: red;" class="far fa-trash-alt"></i></button>
                                    </form>
                                </span>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endisset
@endsection

@section('script')

{{--    @if(route('words.index')=='http://localhost/univ/public/words')--}}
        <script>
            $('#submit').click(function(e){
                e.preventDefault()
                var data = $('#inlineFormInputName').val()

                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    method:'post',
                    url: '{{route("words.store")}}',
                    data: {data, "_token": $('#token').val()},
                    dataType: "json",
                    success: function(json) {
                        if(!json.error) location.reload(true);
                    }
                })
                location.reload(true)

            })
        </script>
    {{--@endif--}}
@endsection